{
 "title": "Spring Boot Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum / http_server_requests_seconds_count"
    }
   ]
  }
 ]
}