apiVersion: v1
kind: ResourceQuota
metadata:
  name: microservices-quota
  namespace: microservices-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "30"
    services: "15"
    persistentvolumeclaims: "15"
    secrets: "30"
    configmaps: "30" 