name: Build Discovery Server

on:
  push:
    branches: [ main ]
    paths:
      - 'discovery-server/**'
      - 'k8s/discovery-server.yaml'
      - '.github/workflows/discovery-server-build.yml'
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  REGISTRY: us-central1-docker.pkg.dev
  REPOSITORY: microservices
  DISCOVERY_SERVER_IMAGE: discovery-server

jobs:
  build-and-deploy:
    name: Build and Deploy Discovery Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build discovery-server with Maven BEFORE Docker build
    - name: Build Discovery Server with Maven
      run: |
        mvn clean package -pl discovery-server -am -DskipTests
        ls -la discovery-server/target/

    # Setup Google Cloud CLI
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Configure Docker to use the gcloud command-line tool as a credential helper
    - name: 'Set up Docker Auth'
      run: |
        gcloud --quiet auth configure-docker
        gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    # Build and push Docker image for discovery-server
    - name: Build and Push Discovery Server Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./discovery-server/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.DISCOVERY_SERVER_IMAGE }}:${{ github.sha }}
        build-args: |
          JAR_FILE=discovery-server/target/*.jar

    # Get the GKE credentials
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # Update discovery-server Kubernetes manifest
    - name: Update Discovery Server Manifest
      run: |
        sed -i "s|image: .*discovery-server.*|image: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.DISCOVERY_SERVER_IMAGE }}:${{ github.sha }}|g" k8s/discovery-server.yaml

    # Deploy discovery-server to GKE
    - name: Deploy Discovery Server to GKE
      run: |
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f k8s/discovery-server.yaml
        
    # Verify deployment
    - name: Verify Deployment
      run: |
        kubectl get pods -n microservices-app | grep discovery-server 