name: Docker Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Monday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  docker-scan:
    name: Docker Image Security Scan
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service: [order-service, inventory-service, product-service, notification-service]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./${{ matrix.service }}
        push: false
        load: true
        tags: ${{ matrix.service }}:scan
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ matrix.service }}:scan
        format: 'sarif'
        output: 'trivy-results-${{ matrix.service }}.sarif'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results-${{ matrix.service }}.sarif'
        
    - name: Run Dockle container linter
      uses: goodwithtech/dockle-action@v0.1.0
      with:
        image: ${{ matrix.service }}:scan
        format: json
        output: dockle-results-${{ matrix.service }}.json
        exit-code: '1'
        exit-level: warn
      continue-on-error: true
        
    - name: Upload Dockle results
      uses: actions/upload-artifact@v3
      with:
        name: dockle-results-${{ matrix.service }}
        path: dockle-results-${{ matrix.service }}.json
