name: GCP Authentication Test

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  auth-test:
    name: Test GCP Authentication
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Google Cloud CLI
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: 'Enable necessary APIs'
      run: |
        gcloud services enable cloudresourcemanager.googleapis.com
        gcloud services enable container.googleapis.com
        gcloud services enable containerregistry.googleapis.com
        gcloud services enable iam.googleapis.com
      continue-on-error: true
      
    - name: 'Print current project'
      run: 'gcloud config get-value project'
      
    - name: 'Verify GKE cluster access'
      run: 'gcloud container clusters list --zone ${{ env.GKE_ZONE }}'
