name: Security Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn -B compile -DskipTests
      
    - name: Run OWASP Dependency-Check
      run: |
        mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=7 -Dformat=HTML -DoutputDirectory=./reports
      continue-on-error: true
      
    - name: Generate security report
      run: |
        echo "# Security Scan Results" > security-report.md
        echo "## Scan completed on $(date)" >> security-report.md
        echo "### Dependency Check Results" >> security-report.md
        echo "- See Maven build logs for details" >> security-report.md
        
    - name: Upload security report
      uses: actions/upload-artifact@v2
      with:
        name: security-report
        path: security-report.md
