name: Security Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache OWASP Dependency-Check data
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run OWASP Dependency-Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'Spring Kafka Microservices'
        path: '.'
        format: 'HTML'
        out: 'reports' # Output directory for reports
        args: >
          --failOnCVSS 7
          --enableRetired
          
    - name: Upload Dependency-Check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        
    - name: Run Maven SpotBugs
      run: mvn spotbugs:check
      continue-on-error: true  # Don't fail the build for SpotBugs issues
      
    - name: Generate security report summary
      if: always()
      run: |
        echo "# Security Scan Results" > security-report.md
        echo "## Scan completed on $(date)" >> security-report.md
        echo "### Dependency Check Results" >> security-report.md
        echo "- See attached HTML report for details" >> security-report.md
        echo "### SpotBugs Results" >> security-report.md
        echo "- Check Maven build logs for details" >> security-report.md
        
    - name: Upload security report summary
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: security-report-summary
        path: security-report.md
